databases:
  - name: pms
    databaseName: mydatabase
    user: proma
    password:
      fromDatabase:
        name: pms
        property: credentials.password

services:
  - type: web
    name: proma
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pms
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
