databases:
  - name: pms
    databaseName: leenproma
    user: proma
    password: RsCRrHUYALLEjC3Qlg6KDuDob6OeVtpA
      fromDatabase :
        name: pms
        property: credentials.password

services:
  - type: web
    name: proma
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"