# Generated by Django 4.1.7 on 2023-03-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        choices=[
                            ("IN", "InProgress"),
                            ("QF", "QuickFinisher"),
                            ("LL", "LazyLoader"),
                            ("SU", "SilentUser"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
            options={"db_table": "badge",},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=100)),
                ("project_decription", models.TextField()),
                ("project_technology", models.CharField(max_length=100)),
                ("project_estimated_hours", models.IntegerField()),
                ("project_start_date", models.DateField()),
                ("project_completion_date", models.DateField()),
                (
                    "project_file",
                    models.FileField(blank=True, null=True, upload_to="project_files/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={"db_table": "project",},
        ),
        migrations.CreateModel(
            name="Project_Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=100)),
                ("module_description", models.TextField()),
                ("module_estimated_hours", models.IntegerField()),
                ("module_start_date", models.DateField()),
                ("module_completion_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={"db_table": "project_module",},
        ),
        migrations.CreateModel(
            name="Project_Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_title", models.CharField(max_length=100)),
                ("task_description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[("High", "High Priority"), ("Less", "Less Priority")],
                        max_length=30,
                    ),
                ),
                ("task_estimated_hours", models.IntegerField()),
                ("task_util_minutes", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={"db_table": "project_task",},
        ),
        migrations.CreateModel(
            name="Project_Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        choices=[
                            ("IN", "InProgress"),
                            ("QF", "QuickFinisher"),
                            ("LL", "LazyLoader"),
                            ("SU", "SilentUser"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
            options={"db_table": "project_team",},
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_name",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={"db_table": "status",},
        ),
        migrations.CreateModel(
            name="Task_Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "task_badge",},
        ),
        migrations.CreateModel(
            name="User_Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
                ("user_totalutil_minutes", models.IntegerField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project_task",
                    ),
                ),
            ],
            options={"db_table": "user_task",},
        ),
    ]
